export const L = {
  donations: 'Donations',
  donationDashboard: 'Donation Dashboard',
  familyName: 'Family Name',
  headOfFamily: 'Head of Family',
  memberCount: 'Members',
  address: 'Address',
  phone: 'Phone',
  cardNumber: 'Family Card No.',
  ward: 'Ward',
  unit: 'Unit',
  monthlyPledge: 'Monthly Pledge',
  annualPledge: 'Annual Pledge',
  annualCollection: 'Annual Collection',
  monthlyCollection: 'Monthly Collection',
  donationType: 'Donation Type',
  memberDonation: 'Member Donation',
  specialDonation: 'Special Donation',
  festivalDonation: 'Festival Donation',
  others: 'Others',
  amount: 'Amount (₹)',
  date: 'Date',
  datePaid: 'Date Paid',
  receipt: 'Receipt',
  receiptNumber: 'Receipt No.',
  register: 'Monthly Register',
  reports: 'Reports',
  topDonors: 'Top 10 Donors',
  defaulters: 'Defaulters',
  total: 'Total',
  grandTotal: 'Grand Total',
  balanceDue: 'Balance Due',
  month: 'Month',
  year: 'Year',
  remarks: 'Remarks',
  save: 'Save',
  cancel: 'Cancel',
  export: 'Export Excel',
  print: 'Print',
  downloadPdf: 'Download PDF',
  recordDonation: 'Record Donation',
  editInfo: 'Edit Info',
  donationInfo: 'Donation Information',
  paymentGrid: 'Payment Grid',
  annualSummary: 'Annual Summary',
  activeDonors: 'Active Donors',
  totalFamilies: 'Total Families',
  wardCollection: 'Ward Collection',
  familySummary: 'Family Summary',
  festivalCollection: 'Festival Collection',
  petersPence: "Peter's Pence",
  yearComparison: 'Year Comparison',
  donorName: 'Donor Name',
  expected: 'Expected',
  paid: 'Paid',
  difference: 'Difference',
  receipts: 'Receipts',
  settings: 'Settings',
  wards: 'Wards',
  units: 'Units',
  donationTypes: 'Donation Types',
  addWard: 'Add Ward',
  addUnit: 'Add Unit',
  addType: 'Add Type',
  seedDefaults: 'Seed Default Types',
  sortOrder: 'Sort Order',
  odiaName: 'Odia Name',
  isRecurring: 'Recurring',
  downloadReceipt: 'Download Receipt',
  viewReceipt: 'View Receipt',
  generateReceipt: 'Generate Receipt',
  dateIssued: 'Date Issued',
  code: 'Code',
  name: 'Name',
  actions: 'Actions',
  months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
} as const;

export function formatINR(amount: number): string {
  return '₹' + amount.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
